name: Wegather-backend workflow

on:
  pull_request:
    branches:
      - master
      - stage

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
  # test:
  #   needs: setup-node
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install Dependencies
  #       run: yarn install --frozen-lockfile
  #     - name: Run test
  #       run: npx jest --coverage | tee ./coverage.txt && exit ${PIPESTATUS[0]}
  #     - name: Jest Coverage Comment
  #       uses: MishaKav/jest-coverage-comment@v1.0.23
  #       with:
  #         coverage-path: ./coverage.txt

  build:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
